; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mcs51 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=MCS51

define i8 @addimm(i8 %a) nounwind {
; MCS51-LABEL: addimm:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, R7
; MCS51-NEXT:    ADD A, #42
; MCS51-NEXT:    RET
  %1 = add i8 %a, 42
  ret i8 %1
}

define i8 @double(i8 %a) nounwind {
; MCS51-LABEL: double:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, R7
; MCS51-NEXT:    ADD A, R7
; MCS51-NEXT:    RET
  %1 = add i8 %a, %a
  ret i8 %1
}

define i8 @add(i8 %a, i8 %b) nounwind {
; MCS51-LABEL: add:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, R7
; MCS51-NEXT:    ADD A, R6
; MCS51-NEXT:    RET
  %1 = add i8 %a, %b
  ret i8 %1
}

define i8 @sub(i8 %a, i8 %b, i8 %c, i8 %d) nounwind {
; MCS51-LABEL: sub:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, R7
; MCS51-NEXT:    CLR C
; MCS51-NEXT:    MOV bit 8, C
; MCS51-NEXT:    SUBB A, R6
; MCS51-NEXT:    MOV R0, A
; MCS51-NEXT:    MOV A, R5
; MCS51-NEXT:    MOV C, bit 8
; MCS51-NEXT:    SUBB A, R4
; MCS51-NEXT:    MOV R7, A
; MCS51-NEXT:    MOV A, R0
; MCS51-NEXT:    ADD A, R7
; MCS51-NEXT:    RET
  %1 = sub i8 %a, %b
  %2 = sub i8 %c, %d
  %3 = add i8 %1, %2
  ret i8 %3
}
