; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mcs51 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=MCS51

define i8 @condbr1(i8 %a) nounwind {
; MCS51-LABEL: condbr1:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, R7
; MCS51-NEXT:    JZ .LBB0_2
; MCS51-NEXT:  ; %bb.1: ; %br1
; MCS51-NEXT:    MOV R7, #27
; MCS51-NEXT:    RET
; MCS51-NEXT:  .LBB0_2: ; %br2
; MCS51-NEXT:    MOV R7, #42
; MCS51-NEXT:    RET
  %tst1 = icmp ne i8 %a, 0
  br i1 %tst1, label %br1, label %br2
br1:
  ret i8 27
br2:
  ret i8 42
}
