; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mcs51 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=MCS51

; Simple functions which can be handled without any moves

define i8 @add1(i8 %a) nounwind {
; MCS51-LABEL: add1:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    INC R7
; MCS51-NEXT:    RET
  %1 = add i8 %a, 1
  ret i8 %1
}

define i8 @sub1(i8 %a) nounwind {
; MCS51-LABEL: sub1:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    DEC R7
; MCS51-NEXT:    RET
  %1 = sub i8 %a, 1
  ret i8 %1
}

