; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mcs51 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=MCS51

define i8 @loadsfr() nounwind {
; MCS51-LABEL: loadsfr:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, 0x82
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 130 to i8*
  %1 = load volatile i8, i8* %sfr
  ret i8 %1
}

define void @storesfr(i8 %x) nounwind {
; MCS51-LABEL: storesfr:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV 0x82, R7
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 130 to i8*
  store volatile i8 %x, i8* %sfr
  ret void
}

define void @incsfr() nounwind {
; MCS51-LABEL: incsfr:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    INC 0x82
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 130 to i8*
  %1 = load i8, i8* %sfr
  %2 = add i8 %1, 1
  store i8 %2, i8* %sfr
  ret void
}

define void @decsfr() nounwind {
; MCS51-LABEL: decsfr:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    DEC 0x82
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 130 to i8*
  %1 = load i8, i8* %sfr
  %2 = sub i8 %1, 1
  store i8 %2, i8* %sfr
  ret void
}

define i8 @volloadplus1(i8 *%a) nounwind {
; MCS51-LABEL: volloadplus1:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV R0, R7
; MCS51-NEXT:    MOV A, @R0
; MCS51-NEXT:    INC R0
; MCS51-NEXT:    MOV A, @R0
; MCS51-NEXT:    RET
  %1 = getelementptr i8, i8 *%a, i8 1
  %2 = load i8, i8* %1
  %3 = load volatile i8, i8* %a
  ret i8 %2
}

define void @immsfrinit() nounwind {
; MCS51-LABEL: immsfrinit:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV 0x82, #127
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 130 to i8*
  store i8 127, i8* %sfr
  ret void
}

define i8 @checkflag() nounwind {
; MCS51-LABEL: checkflag:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV A, 0xe3
; MCS51-NEXT:    ANL A, #64
; MCS51-NEXT:    RET
  %sfr = inttoptr i8 227 to i8*
  %1 = load volatile i8, i8* %sfr
  %2 = and i8 64, %1
  ret i8 %2
}

define void @dir8todir8() nounwind {
; MCS51-LABEL: dir8todir8:
; MCS51:       ; %bb.0:
; MCS51-NEXT:    MOV 0xe4, 0xe3
; MCS51-NEXT:    RET
  %ptr1 = inttoptr i8 227 to i8*
  %ptr2 = inttoptr i8 228 to i8*
  %1 = load volatile i8, i8* %ptr1
  store i8 %1, i8* %ptr2
  ret void
}

